[tool.poetry]
name = "energypy"
version = "0.4.0"
description = ""
authors = ["Adam Green <adam.green@adgefficiency.com>"]

[tool.poetry.dependencies]
python = "3.8.12"
click = "^8.1.2"
imageio = "^2.17.0"
gym = "^0.23.1"
pandas = "1.2.3"
tdqm = "^0.0.1"
pygame = "^2.1.2"
rich = "^12.2.0"
torch = "^1.11.0"
torchvision = "^0.12.0"
tensorflow = "^2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
energypy = 'energypy.main:cli'
