expt:
    name: example

battery: &defaults
    total_steps: 10000

    env:
        env_id: battery
        dataset: example

    agent:
        agent_id: random

cartpole:
    <<: *defaults
    total_steps: 400000

    env:
        env_id: cartpole-v0

    agent:
        agent_id: dqn
        discount: 0.9
        update_target_net: 10000
        tau: 1.0
        batch_size: 512
        layers: 8, 4
        learning_rate: 0.0001
        learning_rate_decay: 1.0
        epsilon_decay_fraction: 0.4
        initial_epsilon: 1.0
        final_epsilon: 0.01
        memory_fraction: 1.0
        memory_type: array
        double_q: True
