name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: test
        run: make test

  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: test examples
        run: make test-examples

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: check
        run: make check

  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: static checks
        run: make static
