name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run tests
      run: make test

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run checks
      run: make check
    - name: Run static
      run: make static -o setup
